#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGZB.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NGZB_db")]
	public partial class ctxDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public ctxDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NGZB_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ctxDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ctxDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ctxDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ctxDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_User")]
		public int I_NGZB_User([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(32)")] string userPass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userCode, userName, userPass, groupID, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_User")]
		public int U_NGZB_User([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(32)")] string userPass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> opType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userCode, userName, userPass, groupID, opType, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.D_NGZB_Role")]
		public int D_NGZB_Role([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleID, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_Role")]
		public int I_NGZB_Role([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string roleName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string roleInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleName, roleInfo, roleID, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.D_NGZB_Role_Item")]
		public int D_NGZB_Role_Item([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleItemID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleItemID, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_Role_User")]
		public int I_NGZB_Role_User([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(60)")] string opUser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleID, userCode, opUser, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_F_File")]
		public int I_NGZB_F_File([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> documentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string fileName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fileUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fileUpUserCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string fileInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentID, fileName, fileUrl, fileUpUserCode, fileInfo, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.D_NGZB_F_File")]
		public int D_NGZB_F_File([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fileID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileID, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_Message")]
		public int I_NGZB_Message([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string msgtitle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string msginfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string msgusercode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), msgtitle, msginfo, msgusercode, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_Model")]
		public int I_NGZB_Model([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string modelControllers, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string modelAction, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), modelControllers, modelAction, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.D_NGZ_F_Document")]
		public int D_NGZ_F_Document([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> documentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> flag, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentID, flag, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_F_Document_M")]
		public int U_NGZB_F_Document_M([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> documentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> targetID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentID, targetID, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_Menu")]
		public int I_NGZB_Menu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> menuParentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> modeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> menuType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string menuImg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string colerCsscClass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), menuParentID, modeID, menuType, menuImg, colerCsscClass, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_Role_Item")]
		public int I_NGZB_Role_Item([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> menuID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(60)")] string appendUserCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleID, menuID, appendUserCode, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.D_NGZB_Menu")]
		public int D_NGZB_Menu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> menuID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), menuID, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_F_DocumentAllow")]
		public int I_NGZB_F_DocumentAllow([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> documentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> allowType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentID, userCode, allowType, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_PersonMsg")]
		public int I_NGZB_PersonMsg([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string msgtitle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string msgInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sendUserCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string recUserCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fileUrl, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), msgtitle, msgInfo, sendUserCode, recUserCode, fileUrl, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_Group")]
		public int I_NGZB_Group([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> groupParentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string groupName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> groupOrderBy, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string groupIcon, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupParentID, groupName, groupOrderBy, groupIcon, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_F_Document_S")]
		public int U_NGZB_F_Document_S([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> documentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentID, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_SystemSet")]
		public int U_NGZB_SystemSet([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string setItme, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string setName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string setValue, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string setInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), setItme, setName, setValue, setInfo, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_F_Document")]
		public int I_NGZB_F_Document([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> documentParentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string documentName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string documentInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> doucmenyorderby, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentParentID, documentName, documentInfo, doucmenyorderby, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_F_Document")]
		public int U_NGZB_F_Document([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> documentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string documentName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string documentInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> doucmenyorderby, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), documentID, documentName, documentInfo, doucmenyorderby, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_MenuGroup")]
		public int I_NGZB_MenuGroup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MenuGroupName", DbType="NVarChar(20)")] string menuGroupName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string menuImg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), menuGroupName, menuImg, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_Menu")]
		public int U_NGZB_Menu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> menuID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> menuParentID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string menuImg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> menuOrderBy, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> menuType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> modeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string colerCsscClass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), menuID, menuParentID, menuImg, menuOrderBy, menuType, modeID, colerCsscClass, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.D_NGZB_Role_User")]
		public int D_NGZB_Role_User([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleUserID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(60)")] string opUser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleUserID, opUser, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_UserLoginOutType")]
		public int I_NGZB_UserLoginOutType([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> actionType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string browerUserHostAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userCode, actionType, browerUserHostAddress, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_UserLoginItem")]
		public int I_NGZB_UserLoginItem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string browerType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string browerBrower, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string browerVersion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> browerVBScript, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> browerCookies, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> browerActiveXControls, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> browerAOL, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string browerUserHostAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string browerUserHostName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> browerDnsSafeHost, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(32)")] string tokenKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isAutoLogin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> loginDate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userCode, browerType, browerBrower, browerVersion, browerVBScript, browerCookies, browerActiveXControls, browerAOL, browerUserHostAddress, browerUserHostName, browerDnsSafeHost, tokenKey, isAutoLogin, loginDate, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(14)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_UserOnLine")]
		public int I_NGZB_UserOnLine([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string userCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> lastOnLineTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(32)")] string tokenKey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userCode, lastOnLineTime, tokenKey, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.D_NGZB_IconList")]
		public int D_NGZB_IconList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_Model")]
		public int U_NGZB_Model([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> modelID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(25)")] string modelName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string modelInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> homeview, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), modelID, modelName, modelInfo, homeview, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.C_NGZB_Init_Group")]
		public int C_NGZB_Init_Group([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string groupName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupName, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.C_NGZB_Init_Menu")]
		public int C_NGZB_Init_Menu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.C_NGZB_Init_Model")]
		public int C_NGZB_Init_Model([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.C_NGZB_Init_Role")]
		public int C_NGZB_Init_Role([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.C_NGZB_Init_User")]
		public int C_NGZB_Init_User([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string adminUsercode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(32)")] string userpass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> groupid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminUsercode, username, userpass, groupid, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.C_NGZB_Init_UserRole")]
		public int C_NGZB_Init_UserRole([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
