#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGZB.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NGZB_db")]
	public partial class ctxEqDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertNGZB_EQ_O_OperateRule(NGZB_EQ_O_OperateRule instance);
    partial void UpdateNGZB_EQ_O_OperateRule(NGZB_EQ_O_OperateRule instance);
    partial void DeleteNGZB_EQ_O_OperateRule(NGZB_EQ_O_OperateRule instance);
    #endregion
		
		public ctxEqDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NGZB_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ctxEqDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ctxEqDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ctxEqDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ctxEqDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NGZB_EQ_O_OperateRule> NGZB_EQ_O_OperateRule
		{
			get
			{
				return this.GetTable<NGZB_EQ_O_OperateRule>();
			}
		}
		
		public System.Data.Linq.Table<V_NGZB_EQ_BaseTree> V_NGZB_EQ_BaseTree
		{
			get
			{
				return this.GetTable<V_NGZB_EQ_BaseTree>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S_NGZB_EQ_BaseTree_GetChild")]
		public ISingleResult<S_NGZB_EQ_BaseTree_GetChildResult> S_NGZB_EQ_BaseTree_GetChild([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eqid);
			return ((ISingleResult<S_NGZB_EQ_BaseTree_GetChildResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S_NGZB_EQ_BaseTree_GetParent")]
		public ISingleResult<S_NGZB_EQ_BaseTree_GetParentResult> S_NGZB_EQ_BaseTree_GetParent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eqid);
			return ((ISingleResult<S_NGZB_EQ_BaseTree_GetParentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_EQ_BaseTree_OperateIsDel")]
		public int U_NGZB_EQ_BaseTree_OperateIsDel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> delType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(4000)")] string whyinfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> opearteType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string opeartUser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eqID, delType, whyinfo, opearteType, opeartUser, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_EQ_BaseTree_Move")]
		public int U_NGZB_EQ_BaseTree_Move([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqParendID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(4000)")] string movewhy, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string opearteUserCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> opearteType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eqID, eqParendID, movewhy, opearteUserCode, opearteType, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_EQ_PassABC")]
		public int I_NGZB_EQ_PassABC([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> abcID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> abcNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> opearteType, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string opeartUser, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eqID, abcID, abcNum, opearteType, opeartUser, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.C_NGZB_EQ_O_OperateRule")]
		public int C_NGZB_EQ_O_OperateRule([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string companTitle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string operateName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string operateCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string operateNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string operateText, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string createUserCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eqID, companTitle, operateName, operateCode, operateNumber, operateText, createUserCode, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_EQ_BaseTree")]
		public int I_NGZB_EQ_BaseTree(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqParendID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(64)")] string eqCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string eqName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(4000)")] string eqInfo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> eqInstallDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string eqIcon, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqOrderBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string nodeOpen, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqClassID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string eqTypeSpecification, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string eqSupplier, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string eqManufacturer, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqIsVirtual, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string opearteUserCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> opearteType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqSpareparts, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqMajor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eqParendID, eqCode, eqName, eqInfo, eqInstallDate, eqIcon, eqOrderBy, nodeOpen, eqClassID, eqTypeSpecification, eqSupplier, eqManufacturer, eqIsVirtual, opearteUserCode, opearteType, eqSpareparts, eqMajor, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(17)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_EQ_BaseTree")]
		public int U_NGZB_EQ_BaseTree(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(64)")] string eqCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string eqName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(4000)")] string eqInfo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> eqInstallDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string eqIcon, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqOrderBy, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string nodeOpen, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqClassID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string eqTypeSpecification, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string eqSupplier, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string eqManufacturer, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqIsVirtual, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string opearteUserCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> opearteType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqSpareparts, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqMajor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eqID, eqCode, eqName, eqInfo, eqInstallDate, eqIcon, eqOrderBy, nodeOpen, eqClassID, eqTypeSpecification, eqSupplier, eqManufacturer, eqIsVirtual, opearteUserCode, opearteType, eqSpareparts, eqMajor, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(17)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.C_NGZB_EQ_O_DayCheckStand")]
		public int C_NGZB_EQ_O_DayCheckStand([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string dayCheckTitle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string checkParts, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(4000)")] string dayCheckInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> checkTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> dayCheckTimeNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> timeNumUnitID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string dayCheckState, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string dayCheckMothed, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string dayCheckStand, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dayCheckID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eqid, dayCheckTitle, checkParts, dayCheckInfo, checkTypeId, dayCheckTimeNum, timeNumUnitID, dayCheckState, dayCheckMothed, dayCheckStand, dayCheckID, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(11)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.C_NGZB_EQ_O_RepairStand")]
		public int C_NGZB_EQ_O_RepairStand([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> repairID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eqID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> repairTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> repairNum, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> unitID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(4000)")] string repairInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(4000)")] string acceptStand, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> repairTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> timeUnitID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string repairtitle, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), repairID, eqID, repairTypeID, repairNum, unitID, repairInfo, acceptStand, repairTime, timeUnitID, repairtitle, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGZB_EQ_O_OperateRule")]
	public partial class NGZB_EQ_O_OperateRule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _eqID;
		
		private string _companTitle;
		
		private string _operateName;
		
		private string _operateCode;
		
		private string _operateNumber;
		
		private string _operateText;
		
		private System.Nullable<int> _isPass;
		
		private string _createUserCode;
		
		private System.Nullable<System.DateTime> _uplastDate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OneqIDChanging(int value);
    partial void OneqIDChanged();
    partial void OncompanTitleChanging(string value);
    partial void OncompanTitleChanged();
    partial void OnoperateNameChanging(string value);
    partial void OnoperateNameChanged();
    partial void OnoperateCodeChanging(string value);
    partial void OnoperateCodeChanged();
    partial void OnoperateNumberChanging(string value);
    partial void OnoperateNumberChanged();
    partial void OnoperateTextChanging(string value);
    partial void OnoperateTextChanged();
    partial void OnisPassChanging(System.Nullable<int> value);
    partial void OnisPassChanged();
    partial void OncreateUserCodeChanging(string value);
    partial void OncreateUserCodeChanged();
    partial void OnuplastDateChanging(System.Nullable<System.DateTime> value);
    partial void OnuplastDateChanged();
    #endregion
		
		public NGZB_EQ_O_OperateRule()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int eqID
		{
			get
			{
				return this._eqID;
			}
			set
			{
				if ((this._eqID != value))
				{
					this.OneqIDChanging(value);
					this.SendPropertyChanging();
					this._eqID = value;
					this.SendPropertyChanged("eqID");
					this.OneqIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companTitle", DbType="NVarChar(50)")]
		public string companTitle
		{
			get
			{
				return this._companTitle;
			}
			set
			{
				if ((this._companTitle != value))
				{
					this.OncompanTitleChanging(value);
					this.SendPropertyChanging();
					this._companTitle = value;
					this.SendPropertyChanged("companTitle");
					this.OncompanTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operateName", DbType="NVarChar(200)")]
		public string operateName
		{
			get
			{
				return this._operateName;
			}
			set
			{
				if ((this._operateName != value))
				{
					this.OnoperateNameChanging(value);
					this.SendPropertyChanging();
					this._operateName = value;
					this.SendPropertyChanged("operateName");
					this.OnoperateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operateCode", DbType="NVarChar(200)")]
		public string operateCode
		{
			get
			{
				return this._operateCode;
			}
			set
			{
				if ((this._operateCode != value))
				{
					this.OnoperateCodeChanging(value);
					this.SendPropertyChanging();
					this._operateCode = value;
					this.SendPropertyChanged("operateCode");
					this.OnoperateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operateNumber", DbType="NVarChar(50)")]
		public string operateNumber
		{
			get
			{
				return this._operateNumber;
			}
			set
			{
				if ((this._operateNumber != value))
				{
					this.OnoperateNumberChanging(value);
					this.SendPropertyChanging();
					this._operateNumber = value;
					this.SendPropertyChanged("operateNumber");
					this.OnoperateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operateText", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string operateText
		{
			get
			{
				return this._operateText;
			}
			set
			{
				if ((this._operateText != value))
				{
					this.OnoperateTextChanging(value);
					this.SendPropertyChanging();
					this._operateText = value;
					this.SendPropertyChanged("operateText");
					this.OnoperateTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isPass", DbType="Int")]
		public System.Nullable<int> isPass
		{
			get
			{
				return this._isPass;
			}
			set
			{
				if ((this._isPass != value))
				{
					this.OnisPassChanging(value);
					this.SendPropertyChanging();
					this._isPass = value;
					this.SendPropertyChanged("isPass");
					this.OnisPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createUserCode", DbType="VarChar(50)")]
		public string createUserCode
		{
			get
			{
				return this._createUserCode;
			}
			set
			{
				if ((this._createUserCode != value))
				{
					this.OncreateUserCodeChanging(value);
					this.SendPropertyChanging();
					this._createUserCode = value;
					this.SendPropertyChanged("createUserCode");
					this.OncreateUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uplastDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> uplastDate
		{
			get
			{
				return this._uplastDate;
			}
			set
			{
				if ((this._uplastDate != value))
				{
					this.OnuplastDateChanging(value);
					this.SendPropertyChanging();
					this._uplastDate = value;
					this.SendPropertyChanged("uplastDate");
					this.OnuplastDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_NGZB_EQ_BaseTree")]
	public partial class V_NGZB_EQ_BaseTree
	{
		
		private int _eqID;
		
		private int _eqParendID;
		
		private string _eqCode;
		
		private string _eqName;
		
		private string _eqABC;
		
		private string _eqInfo;
		
		private System.Nullable<System.DateTime> _eqInstallDate;
		
		private System.Nullable<int> _eqOrderBy;
		
		private string _eqIcon;
		
		private int _eqIsDel;
		
		private string _nodeOpen;
		
		private System.Nullable<int> _eqClassID;
		
		private string _eqTypeSpecification;
		
		private string _eqSupplier;
		
		private string _eqManufacturer;
		
		private string _eqClassName;
		
		private string _eqIsVirtual;
		
		private string _nodeOpentxt;
		
		private System.Nullable<int> _eqSpareparts;
		
		private System.Nullable<int> _eqMajor;
		
		public V_NGZB_EQ_BaseTree()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqID", DbType="Int NOT NULL")]
		public int eqID
		{
			get
			{
				return this._eqID;
			}
			set
			{
				if ((this._eqID != value))
				{
					this._eqID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqParendID", DbType="Int NOT NULL")]
		public int eqParendID
		{
			get
			{
				return this._eqParendID;
			}
			set
			{
				if ((this._eqParendID != value))
				{
					this._eqParendID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqCode", DbType="VarChar(64)")]
		public string eqCode
		{
			get
			{
				return this._eqCode;
			}
			set
			{
				if ((this._eqCode != value))
				{
					this._eqCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string eqName
		{
			get
			{
				return this._eqName;
			}
			set
			{
				if ((this._eqName != value))
				{
					this._eqName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqABC", DbType="VarChar(5)")]
		public string eqABC
		{
			get
			{
				return this._eqABC;
			}
			set
			{
				if ((this._eqABC != value))
				{
					this._eqABC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqInfo", DbType="NVarChar(4000)")]
		public string eqInfo
		{
			get
			{
				return this._eqInfo;
			}
			set
			{
				if ((this._eqInfo != value))
				{
					this._eqInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqInstallDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> eqInstallDate
		{
			get
			{
				return this._eqInstallDate;
			}
			set
			{
				if ((this._eqInstallDate != value))
				{
					this._eqInstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqOrderBy", DbType="Int")]
		public System.Nullable<int> eqOrderBy
		{
			get
			{
				return this._eqOrderBy;
			}
			set
			{
				if ((this._eqOrderBy != value))
				{
					this._eqOrderBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqIcon", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string eqIcon
		{
			get
			{
				return this._eqIcon;
			}
			set
			{
				if ((this._eqIcon != value))
				{
					this._eqIcon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqIsDel", DbType="Int NOT NULL")]
		public int eqIsDel
		{
			get
			{
				return this._eqIsDel;
			}
			set
			{
				if ((this._eqIsDel != value))
				{
					this._eqIsDel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeOpen", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string nodeOpen
		{
			get
			{
				return this._nodeOpen;
			}
			set
			{
				if ((this._nodeOpen != value))
				{
					this._nodeOpen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqClassID", DbType="Int")]
		public System.Nullable<int> eqClassID
		{
			get
			{
				return this._eqClassID;
			}
			set
			{
				if ((this._eqClassID != value))
				{
					this._eqClassID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqTypeSpecification", DbType="NVarChar(1000)")]
		public string eqTypeSpecification
		{
			get
			{
				return this._eqTypeSpecification;
			}
			set
			{
				if ((this._eqTypeSpecification != value))
				{
					this._eqTypeSpecification = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqSupplier", DbType="NVarChar(500)")]
		public string eqSupplier
		{
			get
			{
				return this._eqSupplier;
			}
			set
			{
				if ((this._eqSupplier != value))
				{
					this._eqSupplier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqManufacturer", DbType="NVarChar(500)")]
		public string eqManufacturer
		{
			get
			{
				return this._eqManufacturer;
			}
			set
			{
				if ((this._eqManufacturer != value))
				{
					this._eqManufacturer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqClassName", DbType="NVarChar(50)")]
		public string eqClassName
		{
			get
			{
				return this._eqClassName;
			}
			set
			{
				if ((this._eqClassName != value))
				{
					this._eqClassName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqIsVirtual", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string eqIsVirtual
		{
			get
			{
				return this._eqIsVirtual;
			}
			set
			{
				if ((this._eqIsVirtual != value))
				{
					this._eqIsVirtual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeOpentxt", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string nodeOpentxt
		{
			get
			{
				return this._nodeOpentxt;
			}
			set
			{
				if ((this._nodeOpentxt != value))
				{
					this._nodeOpentxt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqSpareparts", DbType="Int")]
		public System.Nullable<int> eqSpareparts
		{
			get
			{
				return this._eqSpareparts;
			}
			set
			{
				if ((this._eqSpareparts != value))
				{
					this._eqSpareparts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqMajor", DbType="Int")]
		public System.Nullable<int> eqMajor
		{
			get
			{
				return this._eqMajor;
			}
			set
			{
				if ((this._eqMajor != value))
				{
					this._eqMajor = value;
				}
			}
		}
	}
	
	public partial class S_NGZB_EQ_BaseTree_GetChildResult
	{
		
		private System.Nullable<int> _eqID;
		
		private System.Nullable<int> _eqParendID;
		
		private string _eqCode;
		
		private string _eqName;
		
		private string _eqABC;
		
		private string _eqInfo;
		
		private System.Nullable<System.DateTime> _eqInstallDate;
		
		private System.Nullable<int> _eqOrderBy;
		
		private string _eqIcon;
		
		private System.Nullable<int> _eqIsDel;
		
		private string _nodeOpen;
		
		private System.Nullable<int> _eqClassID;
		
		private string _eqTypeSpecification;
		
		public S_NGZB_EQ_BaseTree_GetChildResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqID", DbType="Int")]
		public System.Nullable<int> eqID
		{
			get
			{
				return this._eqID;
			}
			set
			{
				if ((this._eqID != value))
				{
					this._eqID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqParendID", DbType="Int")]
		public System.Nullable<int> eqParendID
		{
			get
			{
				return this._eqParendID;
			}
			set
			{
				if ((this._eqParendID != value))
				{
					this._eqParendID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqCode", DbType="VarChar(64)")]
		public string eqCode
		{
			get
			{
				return this._eqCode;
			}
			set
			{
				if ((this._eqCode != value))
				{
					this._eqCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqName", DbType="NVarChar(100)")]
		public string eqName
		{
			get
			{
				return this._eqName;
			}
			set
			{
				if ((this._eqName != value))
				{
					this._eqName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqABC", DbType="VarChar(5)")]
		public string eqABC
		{
			get
			{
				return this._eqABC;
			}
			set
			{
				if ((this._eqABC != value))
				{
					this._eqABC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqInfo", DbType="NVarChar(4000)")]
		public string eqInfo
		{
			get
			{
				return this._eqInfo;
			}
			set
			{
				if ((this._eqInfo != value))
				{
					this._eqInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqInstallDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> eqInstallDate
		{
			get
			{
				return this._eqInstallDate;
			}
			set
			{
				if ((this._eqInstallDate != value))
				{
					this._eqInstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqOrderBy", DbType="Int")]
		public System.Nullable<int> eqOrderBy
		{
			get
			{
				return this._eqOrderBy;
			}
			set
			{
				if ((this._eqOrderBy != value))
				{
					this._eqOrderBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqIcon", DbType="VarChar(50)")]
		public string eqIcon
		{
			get
			{
				return this._eqIcon;
			}
			set
			{
				if ((this._eqIcon != value))
				{
					this._eqIcon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqIsDel", DbType="Int")]
		public System.Nullable<int> eqIsDel
		{
			get
			{
				return this._eqIsDel;
			}
			set
			{
				if ((this._eqIsDel != value))
				{
					this._eqIsDel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeOpen", DbType="VarChar(6)")]
		public string nodeOpen
		{
			get
			{
				return this._nodeOpen;
			}
			set
			{
				if ((this._nodeOpen != value))
				{
					this._nodeOpen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqClassID", DbType="Int")]
		public System.Nullable<int> eqClassID
		{
			get
			{
				return this._eqClassID;
			}
			set
			{
				if ((this._eqClassID != value))
				{
					this._eqClassID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqTypeSpecification", DbType="NVarChar(2000)")]
		public string eqTypeSpecification
		{
			get
			{
				return this._eqTypeSpecification;
			}
			set
			{
				if ((this._eqTypeSpecification != value))
				{
					this._eqTypeSpecification = value;
				}
			}
		}
	}
	
	public partial class S_NGZB_EQ_BaseTree_GetParentResult
	{
		
		private System.Nullable<int> _eqID;
		
		private System.Nullable<int> _eqParendID;
		
		private string _eqCode;
		
		private string _eqName;
		
		private string _eqABC;
		
		private string _eqInfo;
		
		private System.Nullable<System.DateTime> _eqInstallDate;
		
		private System.Nullable<int> _eqOrderBy;
		
		private string _eqIcon;
		
		private System.Nullable<int> _eqIsDel;
		
		private string _nodeOpen;
		
		private System.Nullable<int> _eqClassID;
		
		private string _eqTypeSpecification;
		
		public S_NGZB_EQ_BaseTree_GetParentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqID", DbType="Int")]
		public System.Nullable<int> eqID
		{
			get
			{
				return this._eqID;
			}
			set
			{
				if ((this._eqID != value))
				{
					this._eqID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqParendID", DbType="Int")]
		public System.Nullable<int> eqParendID
		{
			get
			{
				return this._eqParendID;
			}
			set
			{
				if ((this._eqParendID != value))
				{
					this._eqParendID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqCode", DbType="VarChar(64)")]
		public string eqCode
		{
			get
			{
				return this._eqCode;
			}
			set
			{
				if ((this._eqCode != value))
				{
					this._eqCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqName", DbType="NVarChar(100)")]
		public string eqName
		{
			get
			{
				return this._eqName;
			}
			set
			{
				if ((this._eqName != value))
				{
					this._eqName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqABC", DbType="VarChar(5)")]
		public string eqABC
		{
			get
			{
				return this._eqABC;
			}
			set
			{
				if ((this._eqABC != value))
				{
					this._eqABC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqInfo", DbType="NVarChar(4000)")]
		public string eqInfo
		{
			get
			{
				return this._eqInfo;
			}
			set
			{
				if ((this._eqInfo != value))
				{
					this._eqInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqInstallDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> eqInstallDate
		{
			get
			{
				return this._eqInstallDate;
			}
			set
			{
				if ((this._eqInstallDate != value))
				{
					this._eqInstallDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqOrderBy", DbType="Int")]
		public System.Nullable<int> eqOrderBy
		{
			get
			{
				return this._eqOrderBy;
			}
			set
			{
				if ((this._eqOrderBy != value))
				{
					this._eqOrderBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqIcon", DbType="VarChar(50)")]
		public string eqIcon
		{
			get
			{
				return this._eqIcon;
			}
			set
			{
				if ((this._eqIcon != value))
				{
					this._eqIcon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqIsDel", DbType="Int")]
		public System.Nullable<int> eqIsDel
		{
			get
			{
				return this._eqIsDel;
			}
			set
			{
				if ((this._eqIsDel != value))
				{
					this._eqIsDel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nodeOpen", DbType="VarChar(6)")]
		public string nodeOpen
		{
			get
			{
				return this._nodeOpen;
			}
			set
			{
				if ((this._nodeOpen != value))
				{
					this._nodeOpen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqClassID", DbType="Int")]
		public System.Nullable<int> eqClassID
		{
			get
			{
				return this._eqClassID;
			}
			set
			{
				if ((this._eqClassID != value))
				{
					this._eqClassID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eqTypeSpecification", DbType="NVarChar(2000)")]
		public string eqTypeSpecification
		{
			get
			{
				return this._eqTypeSpecification;
			}
			set
			{
				if ((this._eqTypeSpecification != value))
				{
					this._eqTypeSpecification = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
