#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGZB.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NGZB_db")]
	public partial class ctxSfDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public ctxSfDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NGZB_dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ctxSfDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ctxSfDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ctxSfDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ctxSfDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<V_NGZB_Harm> V_NGZB_Harm
		{
			get
			{
				return this.GetTable<V_NGZB_Harm>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.S_NGZB_SF_Harm")]
		public ISingleResult<S_NGZB_SF_HarmResult> S_NGZB_SF_Harm([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(4000)")] string searchkey, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> workTypeID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchkey, workTypeID);
			return ((ISingleResult<S_NGZB_SF_HarmResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.I_NGZB_SF_Harm")]
		public int I_NGZB_SF_Harm([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> workTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string securityInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string defendAgainst, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string opUserCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), workTypeID, securityInfo, defendAgainst, opUserCode, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.U_NGZB_SF_Harm")]
		public int U_NGZB_SF_Harm([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> safeHarmID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> workTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string securityInfo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string defendAgainst, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string opUserCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> rt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), safeHarmID, workTypeID, securityInfo, defendAgainst, opUserCode, rt);
			rt = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_NGZB_Harm")]
	public partial class V_NGZB_Harm
	{
		
		private int _safeHarmID;
		
		private string _securityInfo;
		
		private string _defendAgainst;
		
		private System.Nullable<int> _workUseCount;
		
		private System.Nullable<int> _workTypeID;
		
		private string _wordTypeName;
		
		public V_NGZB_Harm()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_safeHarmID", DbType="Int NOT NULL")]
		public int safeHarmID
		{
			get
			{
				return this._safeHarmID;
			}
			set
			{
				if ((this._safeHarmID != value))
				{
					this._safeHarmID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_securityInfo", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string securityInfo
		{
			get
			{
				return this._securityInfo;
			}
			set
			{
				if ((this._securityInfo != value))
				{
					this._securityInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defendAgainst", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string defendAgainst
		{
			get
			{
				return this._defendAgainst;
			}
			set
			{
				if ((this._defendAgainst != value))
				{
					this._defendAgainst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workUseCount", DbType="Int")]
		public System.Nullable<int> workUseCount
		{
			get
			{
				return this._workUseCount;
			}
			set
			{
				if ((this._workUseCount != value))
				{
					this._workUseCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workTypeID", DbType="Int")]
		public System.Nullable<int> workTypeID
		{
			get
			{
				return this._workTypeID;
			}
			set
			{
				if ((this._workTypeID != value))
				{
					this._workTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wordTypeName", DbType="NVarChar(500)")]
		public string wordTypeName
		{
			get
			{
				return this._wordTypeName;
			}
			set
			{
				if ((this._wordTypeName != value))
				{
					this._wordTypeName = value;
				}
			}
		}
	}
	
	public partial class S_NGZB_SF_HarmResult
	{
		
		private int _safeHarmID;
		
		private string _securityInfo;
		
		private string _defendAgainst;
		
		private string _wordTypeName;
		
		public S_NGZB_SF_HarmResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_safeHarmID", DbType="Int NOT NULL")]
		public int safeHarmID
		{
			get
			{
				return this._safeHarmID;
			}
			set
			{
				if ((this._safeHarmID != value))
				{
					this._safeHarmID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_securityInfo", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string securityInfo
		{
			get
			{
				return this._securityInfo;
			}
			set
			{
				if ((this._securityInfo != value))
				{
					this._securityInfo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defendAgainst", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string defendAgainst
		{
			get
			{
				return this._defendAgainst;
			}
			set
			{
				if ((this._defendAgainst != value))
				{
					this._defendAgainst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wordTypeName", DbType="NVarChar(500)")]
		public string wordTypeName
		{
			get
			{
				return this._wordTypeName;
			}
			set
			{
				if ((this._wordTypeName != value))
				{
					this._wordTypeName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
